### ISSUE TITLE
[4] Handle proposals related to phishing accounts

### ISSUE THREAD

**Issue by sschiessl-bcp** [blockchainprojects/bitshares-ui#23]
Original issue #1755

- [x] Add toggle in Header of "Proposed transactions": "Deactivate suspicious proposals"
- [x] List of phishing accounts is in app/lib/common/scamAccounts.js, plus blacklist of user (see Burger > Settings > Whitelist)
- [x] If toggle is on, deactive the "Approve" button of such proposals (option to permanently reject remains!)

**Comment by sschiessl-bcp** [comment]
@VerevkinAlexander Please do https://github.com/bitshares/bitshares-ui/issues/2138, I will hold the PR of this issue until it's done, it will facilitate this feature a lot.

You can either write a script or do it by hand.

**Comment by VerevkinAlexander** [comment]
@sschiessl-bcp  I have done Resolve scam accounts to IDs #2138. Also, I added the script for scamAccounts file parsing? but it does not work because can`t get data from api, I think I should do some initialization, but I did not found how. Maybe you can help me with this. Please look at when you have time.

**Comment by VerevkinAlexander** [comment]
PR #32

**Comment by sschiessl-bcp** [comment]
Done with https://github.com/bitshares/bitshares-ui/pull/2178
