### ISSUE TITLE
[9.5][Showcases] Paper Wallet

### ISSUE THREAD

**Issue by sschiessl-bcp** [blockchainprojects/bitshares-ui#30]
Original Issue #2023

Place a button for paper wallet creation next to "Reset" and "Save" in Header of Burger Menu -> Permissions until we have decided where it should actually go

First Task: Investigate PDF creation possibilities

**Comment by VerevkinAlexander** [comment]
I researched the possibility of creation pdf file with dynamic content. it can be performed with jsPdf library. I added the method that receives public and private keys and created a formatted row for pdf with text and QR codes. I a little bit stuck with dynamic elements position because they generate asynchronously. I tried different libraries for qrcode creation but almost all of them are created image asynchronously. @sschiessl-bcp can you help me with logo image for document header? Where I can find it?

**Comment by sschiessl-bcp** [comment]
> I tried different libraries for qrcode creation but almost all of them are created image asynchronously

The UI already has a library to create the QR codes, please use that one. Asynchronous should be no problem, collect the Promises / async calls until all are completed, then start rendering the pdf.

The logo would be easiest to be provided via a SVG file, similar to the Icons. Does that help?

**Comment by VerevkinAlexander** [comment]
https://gyazo.com/e5c32062b3d35d3ca60ff08268b1c3d6

**Comment by VerevkinAlexander** [comment]
> The UI already has a library to create the QR codes, please use that one. Asynchronous should be no problem, collect the Promises / async calls until all are completed, then start rendering the pdf.

sorry for my English. I mean that I am already have resolved those problems and I need the logo image 
https://gyazo.com/46974dcdb6c062e52abe84d2a274b2f7

**Comment by sschiessl-bcp** [comment]
Ah, nice!

Can you try if you can get any of the existing icon (.svg) to be printed in the pdf please? If that works, I will provide you with a .svg with the actual logo

**Comment by VerevkinAlexander** [comment]
I can do this by converting via "canvg"

**Comment by VerevkinAlexander** [comment]
Should be pdf file created with empty private keys if a user is not logged in?

**Comment by sschiessl-bcp** [comment]
I suppose it could be an option to have a public key only wallet. For now force login, we might have different paper wallet styles later on.

**Comment by VerevkinAlexander** [comment]
Can you provide me with a .svg with the actual logo?

**Comment by sschiessl-bcp** [comment]
> Can you provide me with a .svg with the actual logo?

Done, see https://github.com/blockchainprojects/bitshares-ui/commit/a3bd6ae2de3efeb81fce50aacd5b4b25456c9944

**Comment by VerevkinAlexander** [comment]
Thanks 
https://gyazo.com/1a4d7ed114c8d0d6735c03e02d78d960

**Comment by sschiessl-bcp** [comment]
PR #34 accepted and forwarded https://github.com/bitshares/bitshares-ui/pull/2125

**Comment by sschiessl-bcp** [comment]
The npm package canvg has a massive bloat. @VerevkinAlexander please investigate if there are any native alternatives.

I can provide you the header logo also in other picture formats. JSPDF seems to be able to include SVG as well, see here
https://github.com/MrRio/jsPDF/issues/1740#issuecomment-394084681

**Comment by VerevkinAlexander** [comment]
> [MrRio/jsPDF#1740 (comment)](https://github.com/MrRio/jsPDF/issues/1740#issuecomment-394084681)

 This method is used the same canvg.

**Comment by VerevkinAlexander** [comment]
I tried to use .addSvgAsImage(), but no luck . There is some issue inside this method. I debugged it and find that canvg inside this method cant be called because it is not imported to it. Maybe it works only if we add jspdf as a link. Also i tried to use fork from jsPdf (svg2pdf) to add svg file. Also I tried to convert svg to base 64 and give it to jsPdf , add svg as Image -both approaches do not work. I think we can use png file and convert it to base64 and gave it to jspdf.

**Comment by sschiessl-bcp** [comment]
Ok, do you need me to convert anything?

**Comment by VerevkinAlexander** [comment]
> Ok, do you need me to convert anything?

No. Only approve to make it  :-)

**Comment by sschiessl-bcp** [comment]
Yes please.

**Comment by VerevkinAlexander** [comment]
@sschiessl-bcp I changed svg file to png and deleted canvg. Please review it.

**Comment by sschiessl-bcp** [comment]
You accidently changed Exchange.jsx in the corresponding pull request, please make sure not to commit format only changes.

I really like the paperwallet now, this is done!

**Comment by VerevkinAlexander** [comment]
> You accidently changed Exchange.jsx in the corresponding pull request, please make sure not to commit format only changes.

Oh sorry, I don't remember that I commit some Exchange.jsx changes,  maybe this was prettier precommit hook
