### ISSUE TITLE
[6] Exchange Vertical Orderbook rendering warnings

### ISSUE THREAD

**Issue by sschiessl-bcp** [blockchainprojects/bitshares-ui#42]
Original issue #2151

Please investigate which Components produce these Errors. The exchange (https://github.com/bitshares/bitshares-ui/blob/develop/app/components/Exchange/Exchange.jsx) is a beast, try examining the stack trace and code carefully to find out when the warnings are produced.

**Comment by startailcoon** [comment]
Hint to try out https://github.com/bitshares/bitshares-ui/blob/develop/app/components/Exchange/OrderBook.jsx#L39 firstly.

**Comment by VerevkinAlexander** [comment]
@sschiessl-bcp
1 The issue happens because 1 actionCard has no key 
https://github.com/blockchainprojects/bitshares-ui/blob/develop/app/components/Exchange/Exchange.jsx#L2729
Also, similar issue reproduced if switch window with exchange tab from full-screen view to small screen view
https://github.com/blockchainprojects/bitshares-ui/blob/develop/app/components/Exchange/Exchange.jsx#L2695
Adding key={`actionCard_${actionCardIndex++}`}  to both div will resolve those issues.

2 The issue occurs because we use td inside div block
 https://github.com/bitshares/bitshares-ui/blob/develop/app/components/Exchange/OrderBook.jsx#L1268
if replace td by div it stops reproduce. I think td is used because colSpan does not work for sticky-table
Also I found new issue:
![image](https://user-images.githubusercontent.com/43240282/48567384-9218b080-e905-11e8-8cb6-e65dd064e647.png)
It reproduces on the Home tab if switch from full screen to small

**Comment by sschiessl-bcp** [comment]
Please investigate how this could be fixed. Also play around in the Exchange to see if you can find more warnings.

**Comment by VerevkinAlexander** [comment]
Found issue occurs in Tabs.jsx https://github.com/blockchainprojects/bitshares-ui/blob/develop/app/components/Utility/Tabs.jsx#L72 .To fix it we can delete span block and convert title with span type to string type 

```
            if (title.type === "span") {
                title = title.props.children[2];
            }
            return (
                <option value={index} data-is-link-to={this.props.isLinkTo}>                     
                    {title}
                    {updatedTab ? "*" : ""}
                    {subText && " ("}
                    {subText && subText}
                    {subText && ")"}                    
                </option>
            );
```
Also I found 2 new issues. They happens during personalize modal openning 
![image](https://user-images.githubusercontent.com/43240282/48638819-67e4f280-e9da-11e8-96c8-8f41faf5e44b.png)

![image](https://user-images.githubusercontent.com/43240282/48638866-8b0fa200-e9da-11e8-897d-bcdf9ce577b5.png)
They happen because we use an incorrect type of "Select.Option" we use boolean but component expect  string

**Comment by VerevkinAlexander** [comment]
Options do not display.
![image](https://user-images.githubusercontent.com/43240282/48714602-b46b4080-ec1b-11e8-873a-c2df175b50ee.png)

**Comment by sschiessl-bcp** [comment]
Any error messages in log?

**Comment by VerevkinAlexander** [comment]
> Any error messages in log?

There are no error messages in log. I think the reason of issue in my fix of Select.Option issue. I think the problem is in the methods that set value for SELECT component, I need to dig deeper
