### ISSUE TITLE
Integration Testing - Private Login retaining information

### ISSUE THREAD

**Issue by sschiessl-bcp** [blockchainprojects/bitshares-ui#47]
https://github.com/bitshares/bitshares-ui/issues/2176

**Comment by VerevkinAlexander** [comment]
@sschiessl-bcp 

> Chrome:
Logged in with Account X, remember me checked.
Logged in with Account Y, remember me unchecked.
Logged out
Navigated to login - Account Y showing
Refreshed Browser window then went to login - Account X showing.

It is cannot be true because when we disable "Remember me" localStorage does not collect user name  and it cannot be displayed.
I am not sure, but I think that issue can be reproduced when the page updates with path e.g. https://staging.bitshares.org/account/usex_Y_name

**Comment by sschiessl-bcp** [comment]
> It is cannot be true

I could reproduce it, will check it

**Comment by VerevkinAlexander** [comment]
@sschiessl-bcp Please look at, maybe I am doing something wrong?
![20181120180410](https://user-images.githubusercontent.com/43240282/48788165-ebf8ec00-ecf2-11e8-8442-3e683d01b644.gif)
