### ISSUE TITLE
[4] Integration Testing - Edge Browser stuck on Loading

### ISSUE THREAD

**Issue by sschiessl-bcp** [blockchainprojects/bitshares-ui#52]
Original Issue #2175

Please investigate why edge fails to load. I heard that the OpenLedger UI (https://openledger.io/) can open on edge, please try that, also CryptoBridge (https://wallet.crypto-bridge.org/).

**Comment by VerevkinAlexander** [comment]
I found next article http://mikemclin.net/fixing-error-script1028-expected-identifier-string-or-number/ Also The first way is to include a trailing comma after your last property in a JavaScript object. 
build and node_modules have trailing commas
The other common trigger is using a JavaScript reserved word as a property name. - it is not our case

**Comment by VerevkinAlexander** [comment]
One more helpfull article:
 https://stackoverflow.com/questions/44455083/error-script-1028-expected-identifier-string-or-number-with-ie11

**Comment by VerevkinAlexander** [comment]
The issue is not reproduced on September`s release. I found the reasons for those issues It was in webpack.config "jsnext: main" filed and old "alt" libraries. I fixed the issue but IE 11 does not work at all because it is not supported needed technologies. At all, I spent about 8h to find and resolve it During implementation, I found new UI issue on Edge
![image](https://user-images.githubusercontent.com/43240282/48961003-0bee1100-ef7a-11e8-8317-517e20b3c4f1.png)

**Comment by sschiessl-bcp** [comment]
Internet Explorer not working is fine. Edge should work.

**Comment by sschiessl-bcp** [comment]
What was 
`jsnext:main`
used for?

**Comment by VerevkinAlexander** [comment]
> What was
> `jsnext:main`
> used for?

As I know it was needed for supporting ES2015 module syntax, but it is deprecated and was changed on "module"

**Comment by sschiessl-bcp** [comment]
Do you have any sources links for me on that please?

**Comment by VerevkinAlexander** [comment]
https://github.com/jsforum/jsforum/issues/5
https://github.com/rollup/rollup/issues/969

**Comment by sschiessl-bcp** [comment]
Moved to new task
