### ISSUE TITLE
[11.5] Dashboard Portfolio columns

### ISSUE THREAD

**Issue by sschiessl-bcp** [blockchainprojects/bitshares-ui#60]
Original issue ##2311

Use the styleguide tables instead of the existing ones, see for example the explorer. Please contact me if anything is unclear 

Estimate: 7

**Comment by VerevkinAlexander** [comment]
I researched how to change existing data scheme to scheme needed in BitsharesTable. Also, I added a table from bitshares style guide and created a header for it. I've changed data scheme for rows to the new one and created sort methods for columns. I`ve fixed several style issues. Also, I faced with problem when Activity table stops working. It happens because PaginatedList component that I changed previously is used in Activity table too. So I need additional time to research and fix Activity table.

**Comment by VerevkinAlexander** [comment]
Inside RecentTransactions (Activity tab) the is an Operation component that should send rows to the table, but it has wrong data format. So I see 2 ways of implementation:
- to create a parser for data from Operation component
- to fix Operation component but, because it is using in several other components it will take a huge impact

**Comment by sschiessl-bcp** [comment]
Can you create a wrapper for Operation component, that complies to the necessary format? What is wrong?

**Comment by VerevkinAlexander** [comment]
I have researched how Operation component is used in Activity tab rendering. I've created 2 parameters for the Activity table a header and a data source. I was stuck on sending data from Operation component and did not find a method how to take data from operation component. So I decided to create own class OperationAnt.js with needed methods and data. Also, I fixed styles for portfolio and Activity tables. 
In total, I spent on this ticket 23 real hours

**Comment by sschiessl-bcp** [comment]
I forwarded the PR and then noticed that there were many files only reformatted. 

Please check on EVERY commit what files you are committing such that only reformat commits do not happen. This causes massive overhead now when merging with develop branch. Do you have some kind of local reformatting logic enabled?

Furthermore, please see https://github.com/bitshares/bitshares-ui/pull/2644#issuecomment-487532554

**Comment by VerevkinAlexander** [comment]
Sorry, but It happens because we have a pre-commit hook https://github.com/blockchainprojects/bitshares-ui/blob/develop/package.json#L49
